5 5 5 93240
S R R S D S D D S D S U U U L L S D D S U S D D S U U U U S R S R R S D S D D D S U S U U R S D S U L L L S D D D S U U S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S S 0
